// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://syzgnebapaudatybndgu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5emduZWJhcGF1ZGF0eWJuZGd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMDYyNjQsImV4cCI6MjA2OTc4MjI2NH0.O1SOqhejiE0frCEUsSFrz2cMsGl8HdjZ8ZGTkEVBEFw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});